basePath: /api/address
definitions:
  models.Address:
    properties:
      city:
        type: string
      house:
        type: string
      lat:
        type: string
      lon:
        type: string
      street:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.RequestAddressGeocode:
    properties:
      lat:
        type: string
      lng:
        type: string
    type: object
  models.RequestAddressSearch:
    properties:
      query:
        type: string
    type: object
  models.ResponseAddress:
    properties:
      addresses:
        items:
          $ref: '#/definitions/models.Address'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис геокодирования и поиска адресов
  title: Geo Service API
  version: "1.0"
paths:
  /api/address/geocode:
    post:
      consumes:
      - application/json
      description: Возвращает адреса по географическим координатам (широта/долгота)
      parameters:
      - description: Координаты для поиска
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RequestAddressGeocode'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/models.ResponseAddress'
        "400":
          description: Невалидные координаты
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "403":
          description: Вход закрыт
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Обратное геокодирование
      tags:
      - Геоданные
  /api/address/search:
    post:
      consumes:
      - application/json
      description: Возвращает список адресов по строке запроса, используя внешний
        геосервис
      parameters:
      - description: Параметры поиска
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RequestAddressSearch'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/models.ResponseAddress'
        "400":
          description: Невалидный запрос
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "403":
          description: Вход закрыт
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Поиск адреса
      tags:
      - Геоданные
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
